In [ ]:
import numpy as np
import pickle
import pandas as pd
from preprocess1 import *  # this is for loading the .py file which contains all the libraries and the custom functions.
from imblearn.over_sampling import SMOTE
import

ModuleNotFoundError: No module named 'preprocess'

In [ ]:
df=pd.read_csv('titanic.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Sex       418 non-null    object
 3   Age       418 non-null    float64
 4   SibSp     418 non-null    int64
 5   Parch     418 non-null    int64
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB

#  Load the pickle file :

In [ ]:
file=open("Titanic.pkl","rb")

# Load the preprocessor :

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
preprocess1

NameError: name 'preprocess1' is not defined

## This is the preprocessor that was defined in the previous file.

- You can load the preprocessor pipeline  anywhere using the above code for further processsing and for model evaluation.

### What are the further processing steps:

- You need to further check for the null values.
- Correlation between the target columns and the other columns.
- Check for outliers too and if having remove them.
- Scaling the data if needed.
- use transformation if the columns were skewed in distribution.
- splitting the data in train and test.
- Model Creation.
- Model evaluation.
- Hyperparameter Tune the model for the better results.

# Imputing null values :

In [ ]:
df=df.drop(['Ticket','PassengerId','Name','Cabin'], axis=1)

In [ ]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [ ]:
df.loc[df['Age'].isnull(),'Age']=df['Age'].median()

In [ ]:
df.loc[df['Fare'].isnull(),'Fare']=50

In [ ]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

# Transforming the data :

In [ ]:
processed_data=pre.fit_transform(df)

C:\Users\snehr\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
processed_data

array([[ 0.        ,  1.        ,  0.38623105, ...,  0.345     ,
         0.        ,  1.        ],
       [ 1.        ,  0.        ,  1.37137004, ...,  0.47      ,
         1.        ,  2.        ],
       [ 0.        ,  1.        ,  2.55353683, ...,  0.62      ,
         0.        ,  1.        ],
       ...,
       [ 0.        ,  1.        ,  0.70147553, ...,  0.385     ,
         0.        ,  2.        ],
       [ 0.        ,  1.        , -0.20485235, ...,  0.27      ,
         0.        ,  2.        ],
       [ 0.        ,  1.        , -0.20485235, ...,  0.27      ,
         1.        ,  0.        ]])

## Now the dataset is preprocessed and can be used by a model.

                                          ** HAPPY LEARNING **